#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc monitor eDP-1 -d I II III IV
#bspc monitor HDMI-1 -d V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
